### PR TITLE
fix build on case-sensitive filesystems

### PR DESCRIPTION
**Pull request by andir**
The files src/fortran/{input_read,optimization_util}.F90 aren't being covered by the `*.f90` glob in the CMakeLists.txt and thus the build failed on Linux (and likely other systems where the casing of file names matters).

### CODE REVIEW

**Comment by jxjo** [comment]
Thank you!
I will merge in a few days …
Regards
Jochen

**Comment by andir** [comment]
Thanks!

I've added two more commits that make the build a bit more straight forward. Overall I'm really amazed about the results of the tool! Thank you so much for writing this. This is likely the only way I can contribute to it as I'm still learning my way around designing my own profiles.

Let me know if one of the changes it too invasive. I'm also thinking of instructing CMake to install the examples into the `DATADIR` (which is currently defined but never used).

Happy to also look into some CI that automatically builds the project and runs the tests (which currently fail on some decimal place in a test).

**Comment by jxjo** [comment]
Hello Andreas
… very good - thanks!
(cmake is still half a mystery to me)

I use a local release job for building a release including the test run…

**Review by jxjo — COMMENTED** [review]
Ok!

**Comment by jxjo** [comment]
Hello Andreas, 

... I got stucked in merging 😕 There were changes in input_read.f90 in the meantime...
(I also manually renamed the two files F90 into f90)

Could you support? 
Thank you!

**Comment by andir** [comment]
Tooke me a while to get back to this. I've rebased the commits on you latest changes. It should apply without any further conflicts.

**Comment by jxjo** [comment]
Hello Andreas, 

... thank you very much fpr your support!

regards

Jochen

**Pull request merged**
